[package]
name = "kas-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
kas-core.workspace = true
kas-store.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
kas-driver.workspace = true
kas-test-driver = { path = "../kas-test-driver" }
reqwest.workspace = true
tempfile = "3.27.0"
