[package]
name = "kas-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
kas-auth.workspace = true
kas-core.workspace = true
kas-driver.workspace = true
kas-store.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar = "0.4"
tokio = { workspace = true, features = ["process"] }
uuid.workspace = true
url = "2"

[dev-dependencies]
futures-util.workspace = true
kas-test-driver = { path = "../kas-test-driver" }
reqwest.workspace = true
tempfile = "3.27.0"
tokio-tungstenite = { version = "0.29", default-features = false, features = ["connect", "rustls-tls-webpki-roots"] }
